image: docker-registry.xx.network/elixxir/sysadmin/backend-ci:go1.17-wasm

build:
    stage: build
    script:
        - GOOS=js GOARCH=wasm go build -o xxdk.wasm

native-test:
    stage: test
    script:
        - GOOS=js GOARCH=wasm go test ./...
